language: cpp
dist: bionic

jobs:
  include:
    - os: osx
      osx_image: xcode11
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        
before_script:
  - eval "${MATRIX_EVAL}"
  - $CXX --version
  
script:
  - mkdir build && cd ./build
  - cmake ..
  - make
  - cd bin && ./stltest
  
branches:
  only:
  - master
  
notifications:
  email: false
